// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujlprzneifwryqhknaci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqbHByem5laWZ3cnlxaGtuYWNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNjk1MDEsImV4cCI6MjA1OTc0NTUwMX0.HkMLu-cgC46mpanaVk6pukdL849bQ_PYEouvu7Rsdn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);