
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvirhidsamloxpsunnsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52aXJoaWRzYW1sb3hwc3VubnNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxODg5NTMsImV4cCI6MjA2MDc2NDk1M30._SyBqXMunfybbBmBEw-tJHf8WFL9l5KQ90W1X6w_scU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
